### ISSUE TITLE
Linux 4.14 more power hungry?

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-project/nerves_system_rpi3#73] opened 2018-10-08 17:12 UTC
Elixir 1.7.3
Erlang 21
Nerves 1.3
nerves_system_rpi3 1.5

I'm noticing this set of logs:
```
21:42:46.365 [error] [  347.762176] Under-voltage detected! (0x00050005)
[  360.242160] rpi_firmware_get_throttled: 9 callbacks suppressed
[  360.242167] Voltage normalised (0x00000000)

21:42:58.845 [warn]  [  360.242160] rpi_firmware_get_throttled: 9 callbacks suppressed
```

Pretty frequently. I threw a meter on a few different power supplies and i get this message on all of them. My meter is reporting between 4.6 and 5.2 on various power supply and rpi3 combos (including one rpi3 b+). I don't notice any negative impact on performance, but i get this message pretty frequently and i didn't get a similar message on previous kernel versions.

This is probably a non-issue, so feel free to close, just wanted to document for anyone else who notices these logs.

**Comment by jsimmonds2** [comment] 2018-10-12 02:39
The "official" Raspberry Pi power supply provides a 2.5A @5.1V output sustained (I've not checked this).
A Joulescope capture sounds a great thing to do next.   I've also noticed these OS log messages since 4.14

**Comment by fhunleth** [comment] 2018-10-12 04:17
I set my benchtop supply at 2.5A @5.2V and connected up a Raspberry Pi 3 B+ attached to a 7" RPi Touchscreen. Whenever I touch the screen, I get the yellow lightning bolt (undervolt warning) to come on. The bolt disappears as soon as I remove my finger. 

Here's a snapshot from Joulescope. The middle graph (current) is the one to look at. The yellow line is the mean and the two red lines are max and min. As you can see, even when I'm using the touchscreen, the current isn't spiking that high. It's certainly within the capability of my supply. Plus the voltage measurement on the bottom graph doesn't budge:

![nerves-scenic-rpi3-joulescope](https://user-images.githubusercontent.com/64669/46847361-01a0fa80-cdb2-11e8-8f84-271ad466bce2.png)

It's getting late, but I'd like to investigate more and simplify my setup. Something is definitely going on with the lightning bolt.

**Comment by fhunleth** [comment] 2018-10-12 05:02
I made some measurements with Linux 4.9 and it idles 20 mA lower than 4.14. However, that doesn't seem to be good enough to get rid of the lightning bolt for me.

**Comment by jsimmonds2** [comment] 2018-10-12 10:08
Weirdest thing . . I can't reproduce !   (and don't remember whether I saw this first on Raspbian 4.14.74 or on my other 2 RPi3B+ platforms (farmbot_os and my plain Nerves+ElixirALE host) !!)
<sigh>-:

**Comment by fhunleth** [comment] 2018-10-12 15:04
It makes sense. I'm a little disturbed that my benchtop supply still gives lightning bolts, but I'll try buying an official adapter over the weekend just in case.

Also, I found some information here: https://github.com/raspberrypi/linux/issues/2512. Unfortunately, 3/4 of the comments aren't helpful but it does indicate that the undervoltage warnings in the logs are new for Linux 4.14 and provides a few links to explore. 

[Regarding Joulescope, @mliberty1 is trying his best to set up a kickstarter to fund building a batch of them. I don't know when that will go live. He should have a web contact form that you could write him, but I'll bug him to post more details next time I talk with him.]

**Comment by ConnorRigby** [comment] 2018-10-12 15:58
We've noticed the cables used to power the pi are the culprit. Your readings look better than mine however

**Comment by fhunleth** [comment] 2018-10-13 13:50
Yep, it was the cable. I cut the good and bad cables and there's a difference in wire gauge between them. Looks like 28-30 gauge for the bad one vs. 22-24 gauge for the good one? I don't see any lightning bolts, so my conclusion is that there are a LOT of cables floating around with the thinner gauge wire and that the Raspberry Pi is doing the right thing with telling us about it.

However, getting back to the original issue, I measured a 22 mA increase from Linux 4.9 to Linux 4.14 on an RPI3 B+ based kiosk. I don't think I can close the issue yet.

**Comment by fhunleth** [comment] 2018-10-13 13:55
Just to add, in my testing, that 22 mA increase doesn't affect the lightning bolt. I believe the cable is 100% to blame for lightning bolts.

**Comment by fhunleth** [comment] 2021-10-31 15:14
Closing since this is a few years old.

**Closed by fhunleth** 2021-10-31 15:14 UTC
